### ISSUE TITLE
Can't run on v0.89.1+extended darwin/amd64

### ISSUE THREAD

**Issue by gppmad** [themefisher/hargo-hugo#35]
Hi, 

I can't running this template with hugo v0.89.1+extended darwin/amd64 right now.
My laptop is a macbook pro M1 version, and I installed Hugo with brew.

Does anyone have this problem ?

**Comment by somratpro** [comment]
Hello @gppmad 

I am using Hugo v0.89.2_extended and everything runs fine. can you share your error log?
